/*
  # Add Additional Search Terms
  
  1. Changes
    - Inserts approximately 200 traditional Croatian carnival-related terms into searchable_items
    - These terms include costume pieces, musical instruments, dance names, locations, and event-related vocabulary
    - All terms are searchable and will appear in the glossary category
  
  2. Notes
    - Terms are inserted as glossary items (category = 'glossary')
    - All terms use Croatian language (name_local)
    - Each term will link to the glossary page when searched
*/

-- Insert all the new search terms
INSERT INTO searchable_items (name, name_local, description, description_local, category, image_url, display_order) VALUES
('advitor', 'advitor', '', '', 'glossary', NULL, 0),
('arbanaški korak', 'arbanaški korak', '', '', 'glossary', NULL, 0),
('art', 'art', '', '', 'glossary', NULL, 0),
('auditor', 'auditor', '', '', 'glossary', NULL, 0),
('avan', 'avan', '', '', 'glossary', NULL, 0),
('ažur', 'ažur', '', '', 'glossary', NULL, 0),
('bandira', 'bandira', '', '', 'glossary', NULL, 0),
('bandiraš', 'bandiraš', '', '', 'glossary', NULL, 0),
('barilac', 'barilac', '', '', 'glossary', NULL, 0),
('bati', 'bati', '', '', 'glossary', NULL, 0),
('batica', 'batica', '', '', 'glossary', NULL, 0),
('bavul', 'bavul', '', '', 'glossary', NULL, 0),
('be', 'be', '', '', 'glossary', NULL, 0),
('bijelo kolo', 'bijelo kolo', '', '', 'glossary', NULL, 0),
('bisernica', 'bisernica', '', '', 'glossary', NULL, 0),
('bocunić', 'bocunić', '', '', 'glossary', NULL, 0),
('bonboloni', 'bonboloni', '', '', 'glossary', NULL, 0),
('brageše', 'brageše', '', '', 'glossary', NULL, 0),
('Brdasce', 'Brdasce', '', '', 'glossary', NULL, 0),
('bušt', 'bušt', '', '', 'glossary', NULL, 0),
('cimus', 'cimus', '', '', 'glossary', NULL, 0),
('cinta', 'cinta', '', '', 'glossary', NULL, 0),
('crna svilnica', 'crna svilnica', '', '', 'glossary', NULL, 0),
('crveno kolo', 'crveno kolo', '', '', 'glossary', NULL, 0),
('činele', 'činele', '', '', 'glossary', NULL, 0),
('čista sreda', 'čista sreda', '', '', 'glossary', NULL, 0),
('črljena kurdela', 'črljena kurdela', '', '', 'glossary', NULL, 0),
('ćurumbela', 'ćurumbela', '', '', 'glossary', NULL, 0),
('demeškinja', 'demeškinja', '', '', 'glossary', NULL, 0),
('dešpet', 'dešpet', '', '', 'glossary', NULL, 0),
('dešpetljivci', 'dešpetljivci', '', '', 'glossary', NULL, 0),
('dolama', 'dolama', '', '', 'glossary', NULL, 0),
('drelica', 'drelica', '', '', 'glossary', NULL, 0),
('drugi kapitan', 'drugi kapitan', '', '', 'glossary', NULL, 0),
('drugo napovidanje', 'drugo napovidanje', '', '', 'glossary', NULL, 0),
('fidulica', 'fidulica', '', '', 'glossary', NULL, 0),
('fijok', 'fijok', '', '', 'glossary', NULL, 0),
('fris', 'fris', '', '', 'glossary', NULL, 0),
('garoful', 'garoful', '', '', 'glossary', NULL, 0),
('Grabrova', 'Grabrova', '', '', 'glossary', NULL, 0),
('kadina', 'kadina', '', '', 'glossary', NULL, 0),
('Kalvarija', 'Kalvarija', '', '', 'glossary', NULL, 0),
('kantrida', 'kantrida', '', '', 'glossary', NULL, 0),
('kapa', 'kapa', '', '', 'glossary', NULL, 0),
('kapičari', 'kapičari', '', '', 'glossary', NULL, 0),
('kapitan', 'kapitan', '', '', 'glossary', NULL, 0),
('kas', 'kas', '', '', 'glossary', NULL, 0),
('kasir', 'kasir', '', '', 'glossary', NULL, 0),
('kiklija', 'kiklija', '', '', 'glossary', NULL, 0),
('kistice', 'kistice', '', '', 'glossary', NULL, 0),
('kokarda', 'kokarda', '', '', 'glossary', NULL, 0),
('kolarin', 'kolarin', '', '', 'glossary', NULL, 0),
('kolovođa', 'kolovođa', '', '', 'glossary', NULL, 0),
('kopice', 'kopice', '', '', 'glossary', NULL, 0),
('koprivić', 'koprivić', '', '', 'glossary', NULL, 0),
('koraljna ogrlica', 'koraljna ogrlica', '', '', 'glossary', NULL, 0),
('korbač', 'korbač', '', '', 'glossary', NULL, 0),
('kosa', 'kosa', '', '', 'glossary', NULL, 0),
('košulja', 'košulja', '', '', 'glossary', NULL, 0),
('kotiga', 'kotiga', '', '', 'glossary', NULL, 0),
('kotižar', 'kotižar', '', '', 'glossary', NULL, 0),
('krilo', 'krilo', '', '', 'glossary', NULL, 0),
('kripa', 'kripa', '', '', 'glossary', NULL, 0),
('kršćenje mesopusta', 'kršćenje mesopusta', '', '', 'glossary', NULL, 0),
('kurdela', 'kurdela', '', '', 'glossary', NULL, 0),
('kusi', 'kusi', '', '', 'glossary', NULL, 0),
('latica', 'latica', '', '', 'glossary', NULL, 0),
('lira', 'lira', '', '', 'glossary', NULL, 0),
('ljetna nošnja', 'ljetna nošnja', '', '', 'glossary', NULL, 0),
('lustrine', 'lustrine', '', '', 'glossary', NULL, 0),
('lustikovice', 'lustikovice', '', '', 'glossary', NULL, 0),
('magaziner', 'magaziner', '', '', 'glossary', NULL, 0),
('mahramica', 'mahramica', '', '', 'glossary', NULL, 0),
('maitama', 'maitama', '', '', 'glossary', NULL, 0),
('mala gora', 'mala gora', '', '', 'glossary', NULL, 0),
('Mala punta', 'Mala punta', '', '', 'glossary', NULL, 0),
('mala sopila', 'mala sopila', '', '', 'glossary', NULL, 0),
('mali bubanj', 'mali bubanj', '', '', 'glossary', NULL, 0),
('mali mesopustari', 'mali mesopustari', '', '', 'glossary', NULL, 0),
('malo kolo', 'malo kolo', '', '', 'glossary', NULL, 0),
('mandator', 'mandator', '', '', 'glossary', NULL, 0),
('maramica', 'maramica', '', '', 'glossary', NULL, 0),
('mat mesopustova', 'mat mesopustova', '', '', 'glossary', NULL, 0),
('Mel', 'Mel', '', '', 'glossary', NULL, 0),
('mesopusna nedilja', 'mesopusna nedilja', '', '', 'glossary', NULL, 0),
('mesopusni pondiljak', 'mesopusni pondiljak', '', '', 'glossary', NULL, 0),
('mesopusni utorak', 'mesopusni utorak', '', '', 'glossary', NULL, 0),
('mesopustari', 'mesopustari', '', '', 'glossary', NULL, 0),
('mesopustarija', 'mesopustarija', '', '', 'glossary', NULL, 0),
('mesopustarska vičera', 'mesopustarska vičera', '', '', 'glossary', NULL, 0),
('mesopustarska zoga', 'mesopustarska zoga', '', '', 'glossary', NULL, 0),
('Mesopustarsko društvo', 'Mesopustarsko društvo', '', '', 'glossary', NULL, 0),
('mezulanka', 'mezulanka', '', '', 'glossary', NULL, 0),
('Mikulja', 'Mikulja', '', '', 'glossary', NULL, 0),
('misit', 'misit', '', '', 'glossary', NULL, 0),
('mlada mesopustova', 'mlada mesopustova', '', '', 'glossary', NULL, 0),
('mladi', 'mladi', '', '', 'glossary', NULL, 0),
('Mošuna', 'Mošuna', '', '', 'glossary', NULL, 0),
('naćva', 'naćva', '', '', 'glossary', NULL, 0),
('napovidanje', 'napovidanje', '', '', 'glossary', NULL, 0),
('naramenice', 'naramenice', '', '', 'glossary', NULL, 0),
('natezač kola', 'natezač kola', '', '', 'glossary', NULL, 0),
('natikače', 'natikače', '', '', 'glossary', NULL, 0),
('novljanski mesopust', 'novljanski mesopust', '', '', 'glossary', NULL, 0),
('novljansko kolo', 'novljansko kolo', '', '', 'glossary', NULL, 0),
('odgovaralica', 'odgovaralica', '', '', 'glossary', NULL, 0),
('okolo koprivića', 'okolo koprivića', '', '', 'glossary', NULL, 0),
('opanci', 'opanci', '', '', 'glossary', NULL, 0),
('Pepelnica', 'Pepelnica', '', '', 'glossary', NULL, 0),
('picimorti', 'picimorti', '', '', 'glossary', NULL, 0),
('pisak', 'pisak', '', '', 'glossary', NULL, 0),
('pisk', 'pisk', '', '', 'glossary', NULL, 0),
('pivači novljanskoga kola', 'pivači novljanskoga kola', '', '', 'glossary', NULL, 0),
('pivači od kola', 'pivači od kola', '', '', 'glossary', NULL, 0),
('pivačka vičera', 'pivačka vičera', '', '', 'glossary', NULL, 0),
('Placa', 'Placa', '', '', 'glossary', NULL, 0),
('plavo kolo', 'plavo kolo', '', '', 'glossary', NULL, 0),
('plečić', 'plečić', '', '', 'glossary', NULL, 0),
('pletenci', 'pletenci', '', '', 'glossary', NULL, 0),
('poberuhi', 'poberuhi', '', '', 'glossary', NULL, 0),
('pogrebac', 'pogrebac', '', '', 'glossary', NULL, 0),
('poskočnica', 'poskočnica', '', '', 'glossary', NULL, 0),
('praća', 'praća', '', '', 'glossary', NULL, 0),
('prebiralica', 'prebiralica', '', '', 'glossary', NULL, 0),
('Prezidić', 'Prezidić', '', '', 'glossary', NULL, 0),
('prhalja', 'prhalja', '', '', 'glossary', NULL, 0),
('prve divice', 'prve divice', '', '', 'glossary', NULL, 0),
('prvi četvrtak', 'prvi četvrtak', '', '', 'glossary', NULL, 0),
('prijo', 'prijo', '', '', 'glossary', NULL, 0),
('prvi kapitan', 'prvi kapitan', '', '', 'glossary', NULL, 0),
('prvo napovidanje dovcen i dovican', 'prvo napovidanje dovcen i dovican', '', '', 'glossary', NULL, 0),
('rapčin', 'rapčin', '', '', 'glossary', NULL, 0),
('rapčinac', 'rapčinac', '', '', 'glossary', NULL, 0),
('rešt', 'rešt', '', '', 'glossary', NULL, 0),
('rubac', 'rubac', '', '', 'glossary', NULL, 0),
('rukavi na pršut', 'rukavi na pršut', '', '', 'glossary', NULL, 0),
('sarza', 'sarza', '', '', 'glossary', NULL, 0),
('sarzenica', 'sarzenica', '', '', 'glossary', NULL, 0),
('senjski korak', 'senjski korak', '', '', 'glossary', NULL, 0),
('slamnice', 'slamnice', '', '', 'glossary', NULL, 0),
('soljača', 'soljača', '', '', 'glossary', NULL, 0),
('sopci', 'sopci', '', '', 'glossary', NULL, 0),
('sopile', 'sopile', '', '', 'glossary', NULL, 0),
('srednja trumbeta', 'srednja trumbeta', '', '', 'glossary', NULL, 0),
('srednji bubanj', 'srednji bubanj', '', '', 'glossary', NULL, 0),
('stari svati', 'stari svati', '', '', 'glossary', NULL, 0),
('Staro konjsko', 'Staro konjsko', '', '', 'glossary', NULL, 0),
('stomaja', 'stomaja', '', '', 'glossary', NULL, 0),
('studenac', 'studenac', '', '', 'glossary', NULL, 0),
('Stari trg', 'Stari trg', '', '', 'glossary', NULL, 0),
('surka', 'surka', '', '', 'glossary', NULL, 0),
('svaća', 'svaća', '', '', 'glossary', NULL, 0),
('Sveta trojica', 'Sveta trojica', '', '', 'glossary', NULL, 0),
('Sveti Ivan', 'Sveti Ivan', '', '', 'glossary', NULL, 0),
('Sveti Mikulj', 'Sveti Mikulj', '', '', 'glossary', NULL, 0),
('Sveti Rok', 'Sveti Rok', '', '', 'glossary', NULL, 0),
('svilnica', 'svilnica', '', '', 'glossary', NULL, 0),
('svitice', 'svitice', '', '', 'glossary', NULL, 0),
('svitnjak', 'svitnjak', '', '', 'glossary', NULL, 0),
('šajnica', 'šajnica', '', '', 'glossary', NULL, 0),
('Šćedine', 'Šćedine', '', '', 'glossary', NULL, 0),
('šipenica', 'šipenica', '', '', 'glossary', NULL, 0),
('škartoc', 'škartoc', '', '', 'glossary', NULL, 0),
('škrpete', 'škrpete', '', '', 'glossary', NULL, 0),
('špiljica', 'špiljica', '', '', 'glossary', NULL, 0),
('špulet', 'špulet', '', '', 'glossary', NULL, 0),
('štibrica', 'štibrica', '', '', 'glossary', NULL, 0),
('šušur', 'šušur', '', '', 'glossary', NULL, 0),
('švikavac', 'švikavac', '', '', 'glossary', NULL, 0),
('tajke', 'tajke', '', '', 'glossary', NULL, 0),
('tkanica', 'tkanica', '', '', 'glossary', NULL, 0),
('travica', 'travica', '', '', 'glossary', NULL, 0),
('treti četrtak', 'treti četrtak', '', '', 'glossary', NULL, 0),
('trobojnica', 'trobojnica', '', '', 'glossary', NULL, 0),
('treto napovidanje dovcen i dovican', 'treto napovidanje dovcen i dovican', '', '', 'glossary', NULL, 0),
('trojangl', 'trojangl', '', '', 'glossary', NULL, 0),
('tumban', 'tumban', '', '', 'glossary', NULL, 0),
('tusti', 'tusti', '', '', 'glossary', NULL, 0),
('ušici', 'ušici', '', '', 'glossary', NULL, 0),
('vela sopila', 'vela sopila', '', '', 'glossary', NULL, 0),
('vela trumbeta', 'vela trumbeta', '', '', 'glossary', NULL, 0),
('Vele vrata', 'Vele vrata', '', '', 'glossary', NULL, 0),
('veli bubanj', 'veli bubanj', '', '', 'glossary', NULL, 0),
('vidra', 'vidra', '', '', 'glossary', NULL, 0),
('Vinčace', 'Vinčace', '', '', 'glossary', NULL, 0),
('vitica', 'vitica', '', '', 'glossary', NULL, 0),
('vošćilo', 'vošćilo', '', '', 'glossary', NULL, 0),
('Zatrep', 'Zatrep', '', '', 'glossary', NULL, 0),
('zazivače', 'zazivače', '', '', 'glossary', NULL, 0),
('Zeča', 'Zeča', '', '', 'glossary', NULL, 0),
('Zimska nošnja', 'Zimska nošnja', '', '', 'glossary', NULL, 0),
('zobunci', 'zobunci', '', '', 'glossary', NULL, 0),
('zoga', 'zoga', '', '', 'glossary', NULL, 0),
('zračnica', 'zračnica', '', '', 'glossary', NULL, 0),
('zvončići', 'zvončići', '', '', 'glossary', NULL, 0),
('žabice', 'žabice', '', '', 'glossary', NULL, 0),
('žabići', 'žabići', '', '', 'glossary', NULL, 0),
('žgujba', 'žgujba', '', '', 'glossary', NULL, 0),
('žitak', 'žitak', '', '', 'glossary', NULL, 0),
('žmulj', 'žmulj', '', '', 'glossary', NULL, 0),
('župica', 'župica', '', '', 'glossary', NULL, 0);